# action.yml
name: 'Create Package Version'
description: 'Create package version for current repo'
inputs:
  dev-hub:  # devhub url
    description: 'Dev hub secret for authrization in container'
    required: true
  operation: # operation
    description: 'Dev hub secret for authrization in container'
    required: true
runs:
  using: 'docker'
  image: '../docker/Dockerfile'
  args:
    - ${{ inputs.dev-hub }}
    - ${{ inputs.operation }}