# action.yml
name: 'Create Package Version'
description: 'Create package version for current repo'
inputs:
  dev-hub:  # id of input
    description: 'Dev hub secret for authrization in container'
    required: true
runs:
  using: 'docker'
  image: '../docker/Dockerfile'
  args:
    - ${{ secrets.DEV_HUB_CONFIG }}
    #- ${{ inputs.dev-hub }}