# action.yml
name: 'Create DX Package'
description: 'Greet someone and record the time'
inputs:
  dev-hub:  # id of input
    description: 'Dev hub secret for authrization in container'
    required: true
runs:
  using: 'docker'
  image: '../docker/Dockerfile'
  args:
    - ${{ inputs.dev-hub }}