# action.yml
name: 'Perform Action'
description: 'Create docker container and run requested operation'
inputs:
  operation: # operation
    description: 'Process to execute'
    required: true
  imageurl: # url for docker image
    description: 'url for docker image'
    required: true
runs:
  using: 'composite'
  #using: 'composite'
  #image: ${{ inputs.imageurl }} #'../docker/Dockerfile'
  #args:
    #- ${{ inputs.operation }}
    #- ${{ inputs.imageurl }}
  steps:
    - name: Run Container
      run: docker run ${{ inputs.imageurl }}
      shell: bash
    #- name: Run test
    #  run: actions/docker/cli@master
      