# action.yml
name: 'Perform Action'
description: 'Create docker container and run requested operation'
inputs:
  operation: # operation
    description: 'Process to execute'
    required: true
  imageurl: # url for docker image
    description: 'url for docker image'
    required: true
runs:
  using: 'composite'
  #using: 'composite'
  #image: ${{ inputs.imageurl }} #'../docker/Dockerfile'
  #args:
    #- ${{ inputs.operation }}
    #- ${{ inputs.imageurl }}
  steps:
    - name: Run Container
      run: docker run -e DEV_HUB_URL -e BRANCH -e SCRIPTS_PATH 
        --workdir /github/workspace 
        -v "/var/run/docker.sock":"/var/run/docker.sock" 
        -v "/home/runner/work/_temp/_github_home":"/github/home" 
        -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" 
        -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" 
        -v "/home/runner/work/dxgithubworkflow/dxgithubworkflow":"/github/workspace"
        ${{ inputs.imageurl }}
      shell: bash
    #- name: Run test
    #  run: actions/docker/cli@master