# action.yml
name: 'Perform Action'
description: 'Create docker container and run requested operation'
inputs:
  operation: # operation
    description: 'Process to execute'
    required: true
  imageurl: # url for docker image
    description: 'url for docker image'
    required: true
outputs:
  package_version_id:
    description: 'package version id from package creation job'
runs:
  using: 'docker'
  image: '../docker/Dockerfile'
  args:
    - ${{ inputs.operation }}